// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddRecipientController from "./add_recipient_controller"
application.register("add-recipient", AddRecipientController)

import Administrators__RolesController from "./administrators/roles_controller"
application.register("administrators--roles", Administrators__RolesController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import AutocompleteAddressController from "./autocomplete_address_controller"
application.register("autocomplete-address", AutocompleteAddressController)

import CategoryExperienceLevelsController from "./category_experience_levels_controller"
application.register("category-experience-levels", CategoryExperienceLevelsController)

import DuplicatorController from "./duplicator_controller"
application.register("duplicator", DuplicatorController)

import FileDropController from "./file_drop_controller"
application.register("file-drop", FileDropController)

import FilesUploadController from "./files_upload_controller"
application.register("files-upload", FilesUploadController)

import FormSaveController from "./form_save_controller"
application.register("form-save", FormSaveController)

import JobOfferManagementController from "./job_offer_management_controller"
application.register("job-offer-management", JobOfferManagementController)

import JobOfferTermController from "./job_offer_term_controller"
application.register("job-offer-term", JobOfferTermController)

import LocationController from "./location_controller"
application.register("location", LocationController)

import PasswordRulesController from "./password_rules_controller"
application.register("password-rules", PasswordRulesController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import RegulationController from "./regulation_controller"
application.register("regulation", RegulationController)

import RejectionController from "./rejection_controller"
application.register("rejection", RejectionController)

import RemoveRecipientController from "./remove_recipient_controller"
application.register("remove-recipient", RemoveRecipientController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import RfAccordionsManagementController from "./rf_accordions_management_controller"
application.register("rf-accordions-management", RfAccordionsManagementController)

import RfTabManagementController from "./rf_tab_management_controller"
application.register("rf-tab-management", RfTabManagementController)

import RichTooltipController from "./rich_tooltip_controller"
application.register("rich-tooltip", RichTooltipController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import SelectallController from "./selectall_controller"
application.register("selectall", SelectallController)

import SettingsController from "./settings_controller"
application.register("settings", SettingsController)

import SpinnerController from "./spinner_controller"
application.register("spinner", SpinnerController)

import SubcheckboxController from "./subcheckbox_controller"
application.register("subcheckbox", SubcheckboxController)

import TimeoutableController from "./timeoutable_controller"
application.register("timeoutable", TimeoutableController)

import ToggleVisibilityController from "./toggle_visibility_controller"
application.register("toggle-visibility", ToggleVisibilityController)

import TrixEditorController from "./trix_editor_controller"
application.register("trix-editor", TrixEditorController)

import TrixErrorsController from "./trix_errors_controller"
application.register("trix-errors", TrixErrorsController)

import ZipFilePollingController from "./zip_file_polling_controller"
application.register("zip-file-polling", ZipFilePollingController)
