inherit_from: []

inherit_gem:
  standard: config/base.yml

require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/{bundle,rails,rake,setup,spring,update,webpack,webpack-dev-server}'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
