inherit_from: .rubocop_todo.yml

inherit_gem:
  standard: config/base.yml

require:
  - standard
plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "bin/{bundle,rails,rake,setup,spring,update}"
    - "db/**/*"
    - "node_modules/**/*"
    - "vendor/bundle/**/*"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/AnyInstance:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  AllowSubject: true
  Max: 7

Rails/StrongParametersExpect:
  Enabled: false
