version: '2'
services:
  postgresql:
    image: scalingo/postgresql:10.3.0-1
    ports:
      - 5432:5432
    environment:
      DB_UID: 1000
    volumes:
      - ./docker/postgresql-data:/var/lib/postgresql:rw
    command: /postgresql
  web:
    build: .
    volumes:
      - .:/usr/src/app:rw
      - ./docker/ssh:/root/.ssh:ro
    environment:
      PRODUCTION_SERVER_IP: "${PRODUCTION_SERVER_IP}"
      PRODUCTION_SERVER_USER: "${PRODUCTION_SERVER_USER}"
      DEFAULT_HOST: "${DEFAULT_HOST}"
      MAIL_URL: "${MAIL_URL}"
      DATABASE_URL: postgresql://admin:admin-secret@postgresql:5432/civilsdeladefense_development
      DATABASE_URL_TEST: postgresql://admin:admin-secret@postgresql:5432/civilsdeladefense_test
      BUNDLE_BIN: "/usr/src/app/vendor/.bundle/ruby/2.5.0/bin"
      BUNDLE_PATH: "/usr/src/app/vendor/.bundle/ruby/2.5.0"
      BUNDLE_APP_CONFIG: "/usr/src/app/.bundle"
      WEBPACKER_DEV_SERVER_HOST: 172.17.0.1
    links:
      - postgresql
      - webpack
    ports:
      - 3000:3000
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  webpack:
    build: .
    ports:
      - 3035:3035
    volumes:
      - ./:/usr/src/app
    command: bundle exec ./bin/webpack-dev-server
    environment:
      BUNDLE_BIN: "/usr/src/app/vendor/.bundle/ruby/2.5.0/bin"
      BUNDLE_PATH: "/usr/src/app/vendor/.bundle/ruby/2.5.0"
  specs:
    build: .
    volumes:
      - ./:/usr/src/app/
    environment:
      RAILS_ENV: test
      MAIL_URL: smtp://hello%40localhost@localhost
      DEFAULT_HOST: http://localhost:3000
      DATABASE_URL_TEST: postgresql://admin:admin-secret@postgresql:5432/civilsdeladefense_test
      BUNDLE_BIN: "/usr/src/app/vendor/.bundle/ruby/2.5.0/bin"
      BUNDLE_PATH: "/usr/src/app/vendor/.bundle/ruby/2.5.0"
      BUNDLE_APP_CONFIG: "/usr/src/app/.bundle"
    links:
      - postgresql
    command: "tail -F /dev/null"
