version: '2'
services:
  postgresql:
    image: scalingo/postgresql:10.4.0-1
    ports:
      - 5432:5432
    environment:
      DB_UID: 1000
    volumes:
      - ./docker/postgresql-data:/var/lib/postgresql:rw
    command: /postgresql
  web:
    build: .
    volumes:
      - .:/usr/src/app:rw
      - ./docker/ssh:/root/.ssh:ro
    environment:
      ALGOLIA_APP_ID: "${ALGOLIA_APP_ID}"
      ALGOLIA_API_KEY: "${ALGOLIA_API_KEY}"
      DATABASE_URL: postgresql://admin:admin-secret@postgresql:5432/civilsdeladefense_development
      DATABASE_URL_TEST: postgresql://admin:admin-secret@postgresql:5432/civilsdeladefense_test
      DEFAULT_FROM: "${DEFAULT_FROM}"
      DEFAULT_HOST: "${DEFAULT_HOST}"
      LOCKBOX_MASTER_KEY: "${LOCKBOX_MASTER_KEY}"
      MAIL_URL: "${MAIL_URL}"
      OSC_AK: "${OSC_AK}"
      OSC_SK: "${OSC_SK}"
      OSC_BUCKET: "${OSC_BUCKET}"
      OSC_REGION: "${OSC_REGION}"
      OSC_ENDPOINT: "${OSC_ENDPOINT}"
      SEED_PASSWORD: "${SEED_PASSWORD}"
      WEBPACKER_DEV_SERVER_HOST: 172.17.0.1
    links:
      - postgresql
      - webpack
    ports:
      - 3000:3000
    command: rails server -b 0.0.0.0 -p 3000
  webpack:
    build: .
    ports:
      - 3035:3035
    volumes:
      - ./:/usr/src/app
    command: ./bin/webpack-dev-server
    environment:
      ALGOLIA_APP_ID: "${ALGOLIA_APP_ID}"
      ALGOLIA_API_KEY: "${ALGOLIA_API_KEY}"
  specs:
    build: .
    volumes:
      - ./:/usr/src/app/
    environment:
      DEFAULT_FROM: hello@localhost
      DEFAULT_HOST: http://localhost:3000
      DATABASE_URL_TEST: postgresql://admin:admin-secret@postgresql:5432/civilsdeladefense_test
      LOCKBOX_MASTER_KEY: 0000000000000000000000000000000000000000000000000000000000000000
      MAIL_URL: smtp://hello%40localhost@localhost
      RAILS_ENV: test
    links:
      - postgresql
    command: "tail -F /dev/null"
