name: Testing with RSpec
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Set up database
        run: bundle exec rails db:schema:load

      - name: Compile assets
        run: |
          bundle exec rails tmp:clear
          bundle exec rails assets:precompile

      - name: RSpec
        run: bundle exec rspec --fail-fast --format documentation
        env:
          SMTP_URL: smtp://hello%40localhost@localhost
          LOCKBOX_MASTER_KEY: 0000000000000000000000000000000000000000000000000000000000000000
          DEFAULT_FROM: hello@localhost
          DEFAULT_HOST: http://localhost:3000
          FRANCE_CONNECT_HOST: not.a.real.host.test-franceconnect.fr
          SECURE_CONTENT: true
